#!/bin/bash
# Specify jobname:
#SBATCH --job-name=Joseph
# Specify the number of nodes and the number of CPU's (tasks) per node:
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH -p normal
# Specify account. 
!#SBATCH --account=
# The maximum time allowed for the job, in hh:mm:ss
#SBATCH --time=24:00:00
# Maximum memory allowed per cpu
#SBATCH --mem-per-cpu=4G

## Run command 
mpirun -np 20 pw.x -inp 3-zgnr_bands.in > 3-zgnr_bands.out

exit 0
