#!/bin/bash
# Specify jobname:
#SBATCH --job-name=Joseph
# Specify the number of nodes and the number of CPU's (tasks) per node:
#SBATCH --nodes=1
#SBATCH --ntasks=24
#SBATCH -p medio
# Specify account. 
!#SBATCH --account=
# The maximum time allowed for the job, in hh:mm:ss
#SBATCH --time=24:00:00
# Maximum memory allowed per cpu
#SBATCH --mem-per-cpu=4G

## Run command 
mpirun -np 24 projwfc.x -inp grap_SOC_projwfc.in > grap_SOC_projwfc.out

exit 0
