#!/bin/bash
# Specify jobname:
#SBATCH --job-name=Joseph
# Specify the number of nodes and the number of CPU's (tasks) per node:
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH -p normal
# The maximum time allowed for the job, in hh:mm:ss
#SBATCH --time=24:00:00

## Run command 
mpirun -np 20 pw.x -inp grap_SOC_scf.in > grap_SOC_scf.out

exit 0
